### ISSUE TITLE
Can't install etas package

### ISSUE THREAD

**Issue by hanzp-create** [lmizrahi/etas#10]
Why can't my python3.8 install the etas package? What is the name of the specific package? Thanks!

**Comment by lmizrahi** [comment]
hi! it's actually not a package yet. so you would have to clone the repository using `git clone https://github.com/lmizrahi/etas.git` and then install it by navigating into the repository `(cd etas/)` and doing `pip install -e .`

**Comment by hanzp-create** [comment]
ok. thanks a lot for the tip!
